### ISSUE TITLE
InvalidCastException on Windows Server 2008 R2

### ISSUE THREAD

**Issue by Akzentianer** [josemesona/ManagedDism#25]
If I run my project on a Windows Server 2008 R2 machine I get this Exception:

System.InvalidCastException: Die angegebene Umwandlung ist ungültig.
   bei Microsoft.Dism.DismApi.ThrowIfFail(Func`1 func, Int32[] successCodes) in :Zeile 0.
   bei Akzentum.InstallHelper.FeatureManipulator.ManipulateWindowsFeature(String[] features)

Feature: IIS-WebServerRole
Package: Microsoft-Windows-Foundation-Package\~31bf3856ad364e35\~amd64\~\~6.1.7601.17514

Befor I could run my project I had to install the ADK from Microsoft, because the dismapi.dll isn't installed by default.
[https://www.microsoft.com/de-de/download/details.aspx?id=39982](url)

On a Windows Server 2012 and higher everything works fine so far.

Kind regards.

**Comment by Shidell** [comment]
Just to confirm, the error you cited above is what's thrown when you call DismApi.Initialize(), correct?

I believe you're having this problem because DISM isn't natively available on Server 2008 R2, and is instead in a separate Program Files folder.

If you can verify, I'm looking into solution(s).

**Comment by Akzentianer** [comment]
Hello Shidell,

I'm very sorry that it took me so long to verify your solution, unfortunately I still have this cast issue.

But now I have a bit more detailed Stacktrace, the exceptions happens whild EnableFeature.

System.InvalidCastException: Specified cast is not valid.
   bei Microsoft.Dism.DismApi.ThrowIfFail(Func`1 func, Int32[] successCodes)
   bei Microsoft.Dism.DismApi.ThrowIfFail(Func`1 func)
   bei Microsoft.Dism.DismApi.EnableFeature(DismSession session, String featureName, String identifier, DismPackageIdentifier packageIdentifier, Boolean limitAccess, Boolean enableAll, List`1 sourcePaths, DismProgressCallback progressCallback, Object userData)
   bei Microsoft.Dism.DismApi.EnableFeatureByPackageName(DismSession session, String featureName, String packageName, Boolean limitAccess, Boolean enableAll, List`1 sourcePaths, DismProgressCallback progressCallback, Object userData)
   bei Microsoft.Dism.DismApi.EnableFeatureByPackageName(DismSession session, String featureName, String packageName, Boolean limitAccess, Boolean enableAll, List`1 sourcePaths, DismProgressCallback progressCallback)
   bei Microsoft.Dism.DismApi.EnableFeatureByPackageName(DismSession session, String featureName, String packageName, Boolean limitAccess, Boolean enableAll)
   bei Akzentum.InstallHelper.FeatureManipulator.ManipulateWindowsFeature(String[] features)

Kind Regards

**Comment by Shidell** [comment]
@Akzentianer 

I've created a new branch "add-dism-utilities-support" from my fork. @josemesona and I have been discussing how to properly implement this new "utility" class, to add support for external DISM libraries, in a manner that makes sense:

https://github.com/Shidell/ManagedDism/tree/add-dism-utilities-support

I would invite you to clone this fork and try using the DismUtilities class (read the comments first) to load DISM and report back your findings, as I expect this should solve the problem you're having. but having your experience and testing on 2008 would be a great test.

**Comment by Akzentianer** [comment]
Hello Shidell,

I've downloaded your new branch but I still get an invalidcast exception.

Here are the function I call and the parameter values. I hope this helps a bit.
featuresList = "IIS-WebServerRole"
packageGroup.Key = "Microsoft-Windows-Foundation-Package\~31bf3856ad364e35\~amd64\~\~6.1.7601.17514"

dismSession = dismSession
{Microsoft.Dism.DismSession}
    IsClosed: false
    IsInvalid: false
    _fullyInitialized: true
    _ownsHandle: true
    _state: 4
    handle: {2} = m_values = 0x0000000000000002
                         Static members = IntPtr.Zero
DismApi.EnableFeatureByPackageName(dismSession,featuresList, packageGroup.Key,/\*limitaccess\*/ false, /\*enableALL\*/ true);

"System.InvalidCastException" in Microsoft.Dism.dll
System.InvalidCastException: Specified cast is not valid.

   bei Microsoft.Dism.DismApi.ThrowIfFail(Func`1 func, Int32[] successCodes) in L:\Downloads\ManagedDism-add-dism-utilities-support\ManagedDism-add-dism-utilities-support\src\Microsoft.Dism\DismApi.cs:Line 1413.
   
   bei Microsoft.Dism.DismApi.ThrowIfFail(Func`1 func) in L:\Downloads\ManagedDism-add-dism-utilities-support\ManagedDism-add-dism-utilities-support\src\Microsoft.Dism\DismApi.cs:Line 1392.
   
   bei Microsoft.Dism.DismApi.EnableFeature(DismSession session, String featureName, String identifier, DismPackageIdentifier packageIdentifier, Boolean limitAccess, Boolean enableAll, List`1 sourcePaths, DismProgressCallback progressCallback, Object userData) in L:\Downloads\ManagedDism-add-dism-utilities-support\ManagedDism-add-dism-utilities-support\src\Microsoft.Dism\DismApi.cs:Line 1439.
   
   bei Microsoft.Dism.DismApi.EnableFeatureByPackageName(DismSession session, String featureName, String packageName, Boolean limitAccess, Boolean enableAll, List`1 sourcePaths, DismProgressCallback progressCallback, Object userData) in L:\Downloads\ManagedDism-add-dism-utilities-support\ManagedDism-add-dism-utilities-support\src\Microsoft.Dism\DismApi.cs:Line 363.
   
   bei Microsoft.Dism.DismApi.EnableFeatureByPackageName(DismSession session, String featureName, String packageName, Boolean limitAccess, Boolean enableAll, List`1 sourcePaths, DismProgressCallback progressCallback) in L:\Downloads\ManagedDism-add-dism-utilities-support\ManagedDism-add-dism-utilities-support\src\Microsoft.Dism\DismApi.cs:Line 344.
   
   bei Microsoft.Dism.DismApi.EnableFeatureByPackageName(DismSession session, String featureName, String packageName, Boolean limitAccess, Boolean enableAll) in L:\Downloads\ManagedDism-add-dism-utilities-support\ManagedDism-add-dism-utilities-support\src\Microsoft.Dism\DismApi.cs:Line 310.

Kind Regards

**Comment by Shidell** [comment]
Just wanted to let you know, I'm working on setting up a Server 2008 R2 x64 virtual machine to try and test out your issue--just haven't finished it quite yet. I'm hoping to get to it within the next week, though.

**Comment by Akzentianer** [comment]
I still get this error on a Windows Server 2008 R2.

I tracked down where this is happening and I found this line:

`return Marshal.GetExceptionForHR(errorCode);` 

it is in the file DismException.cs line 66.

The issue is that the errorCode is -2147467262.

This is because in this Line:
`int hresult = func();` 
the func return is  -2147467262.

This is in DismApi.cs line 1412.

The reason why the hresult is negativ is because hresult is int and not long , I changed this and everything around the function ThrowIfFail and in the NativeMethods.cs to long (return type only) and the I got displayed this error number "2147500034".

As far as I can see this error is returned from WUSA and means that something is not support. 

Kind regards

**Comment by jeffkl** [comment]
I believe the `InvalidCastException` is happening somewhere else.

Although it does appear that the `Int32` is overflowing, its still properly represented as `-2147467262`.  Under the debugger, I can see that these values are equivilent:

```cs
int i = -2147467262;
uint x = 2147500034;
```

The only difference is how they are printed but they are byte for byte the same

![image](https://user-images.githubusercontent.com/17556515/41624423-7b59fc6a-73ca-11e8-9349-634f3d53597e.png)

And the `Int64` version is also the same byte-wise:

```cs
long y = 2147500034;
```

![image](https://user-images.githubusercontent.com/17556515/41624461-9ed7e99a-73ca-11e8-9fca-165a391403be.png)

All other Dism interop implementations I can find use an `Int32` including the PowerShell CmdLets that Microsoft ships.

`C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Dism\Microsoft.Dism.PowerShell.dll`

```cs
// Microsoft.Dism.Commands.DismInterop
using System.Runtime.InteropServices;

[DllImport("dismapi.dll")]
public static extern int DismInitialize(LogLevel LogLevel, [MarshalAs(UnmanagedType.LPWStr)] string LogFilePath, [MarshalAs(UnmanagedType.LPWStr)] string ScratchDirectory);
```

I haven't been able to repro the issue yet, do you get an error using the PowerShell CmdLet or `dism.exe`?
